# Generated by Django 2.1.5 on 2019-01-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts_images'),
        ),
    ]
